version: "3.11"
name: "nodejs-api-template-testing-dependencies"
services:
    postgres_db:
        container_name: "api_test_postgres_db"
        image: "postgres:15"
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=nodejs_api_template_db
